FROM node:18-slim
WORKDIR /workspace
RUN apt-get update -y && apt-get install -y openssl
# COPY --from=cache /workspace/node_modules /workspace/node_modules
RUN yarn global add prisma

# Copy prisma directory and run prisma generate
COPY prisma/ ./prisma/
RUN prisma generate

# CMD prisma migrate deploy && prisma db seed
CMD prisma migrate deploy
