version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.32
    volumes:
      - ./etc/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    healthcheck:
      test: mysqladmin ping -h mysql -uroot

  server:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.local
      network: host
    volumes:
      - .:/workspace
      - nestjs-node-modules:/workspace/node_modules
    ports:
      - 4000:4000
    depends_on:
      mysql:
        condition: service_healthy
      # migrate:
      #   condition: service_completed_successfully
    env_file:
      - .env
    tty: true

  # migrate:
  #   platform: linux/x86_64
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.migrate
  #     network: host
  #   environment:
  #     - MYSQL_HOST=mysql
  #     - MYSQL_USER=root
  #     - MYSQL_PORT=13306
  #     - MYSQL_PASSWORD=
  #     - MYSQL_DATABASE=nestjest
  #     - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

volumes:
  mysql-db:
  nestjs-node-modules:
